oz-4team/bbang-fe

src/layout/MainLayout.jsx

:sparkles: 레이아웃 세팅 시작

---

src/App.jsx
src/pages/LoginPage.jsx

🐛 Login sigup

---

src/App.jsx
src/pages/SignUpPage.jsx
src/pages/SignupCompletedPage.jsx
src/styles/SignupComplete.css

회원가입 페이지 -> 회원가입 완료 페이지 -> 로그인 페이지

✨ 회원가입 완료 페이지

---

src/App.jsx
src/api/authApi.js
src/pages/ForgotPasswordPage.jsx
src/pages/SignUpPage.jsx
src/store/userStore.js

🐛 Test Signup

---

.env
src/api/authApi.js
src/api/socialAuthApi.js
src/pages/SignUpPage.jsx
src/store/userStore.js

🐛 SocialApi fix

---

package-lock.json
package.json
src/App.jsx
src/components/ArtistCard.jsx
src/components/MyArtistFilterCard.jsx
src/components/ScheduleList.jsx
src/components/ScheduleListItem.jsx
src/pages/SchedulePage.jsx
src/pages/SignUpPage.jsx

react-calendar 설치했으니
npm install 꼭 해주세요~~!

Feature/스케줄페이지 레이아웃(기능없음)

---

src/api/authApi.js
src/api/socialAuthApi.js
src/components/SocialLogin.jsx
src/pages/LoginPage.jsx
src/store/userStore.js
src/utils/authUtils.js

wip socialAPi

---

src/api/authApi.js
src/api/googleAuthApi.js
src/api/naverAuthApi.js
src/pages/AuthCallback.jsx
src/pages/LoginPage.jsx

⚡️ IsStaff

---

src/pages/ProfilePage.jsx
src/styles/Profile.css
src/styles/SignupForm.css

유저 닉네임, 이메일 가져오기 (프로필 이미지 크기 조정해야함)
닉네임 중복버튼 삭제

✨ 회원정보 수정 페이지 수정

---

src/pages/ProfilePage.jsx
src/styles/Profile.css

✨ 프로필 사진 클래스 변경

---

src/App.jsx
src/api/axiosInterceptors.js
src/api/googleAuthApi.js
src/api/naverAuthApi.js
src/components/ArtistCardArea.jsx
src/components/Navigation.jsx
src/components/ScheduleCardArea.jsx
src/components/SocialLogin.jsx
src/pages/AdminRequestPage.jsx
src/utils/authUtils.js
src/utils/validation.js

✨ Token,Automatic logout

---

src/api/authApi.js
src/components/MyArtistFilter.jsx
src/pages/AuthCallback.jsx
src/pages/ProfilePage.jsx
src/store/userStore.js

🐛 Profileimage

---

package-lock.json
package.json
src/pages/ArtistManagementPage.jsx
src/styles/ArtistManagementPage.css

✨ 아티스트 관리 페이지 수정

---

src/pages/SignUpPage.jsx

약관페이지 들어갔다 왔을 때 입력했던 필드값 초기화 방지
BBFE-55

🐛 Fix : 페이지 초기화 수정

---

src/App.jsx
src/api/authApi.js
src/api/axiosInterceptors.js
src/pages/EmailSuccess.jsx
src/pages/SignUpPage.jsx
src/utils/authUtils.js
src/utils/validation.js

🐛 Main.jsx import

---

src/api/authApi.js
src/components/Navigation.jsx
src/store/userStore.js

적용을안시키고있었음..
로컬에 중복 저장되는 토큰 삭제
+로그아웃시 모든 토큰 ,유저 인포 삭제

✨ LogoutApi

---

src/api/authApi.js
src/store/userStore.js

🐛 UseStoreRfactor

---

src/pages/SignUpPage.jsx
src/styles/SignupForm.css

**어떤 변경사항인가요?**
회원가입시 이메일 중복 시 알림 모달 추가
**관련된 이슈**
BBFE-61

✨ Feat : 이메일 중복 알림 모달 추가

---

src/pages/LoginPage.jsx
src/styles/login.css

이메일 인증 안됐을 경우 인증을 완료 해달라는 모달 뜨게 추가
오류코드 BBFE-62

✨ Feat : 이메일 인증 알림 모달

---

src/api/authApi.js
src/pages/ForgotPasswordPage.jsx
src/styles/ForgotPassword.css

✨ Feat : 이메일인증링크 10분 쿨탐 추가

---

src/api/schedule/scheduleApi.js
src/api/schedule/useFavorites.js
src/components/ScheduleCard.jsx

🐛 Fix favorites

---

src/components/ArtistCardArea.jsx
src/components/ScheduleCard.jsx
src/components/SearchBar.jsx
src/pages/ArtistListPage.jsx
src/pages/LoginPage.jsx
src/styles/ArtistCardArea.css

아티스트 검색 기능 추가 및 css 분리
BBFE-74

Feat : 아티스트 검색 기능 추가

---

src/App.jsx
src/components/ScheduleListItem.jsx
src/pages/ScheduleDetailPage.jsx
src/pages/ScheduleEditPage.jsx
src/pages/admin/schedule/Index.jsx
src/pages/admin/schedule/ScheduleAddPage.jsx
src/pages/admin/schedule/ScheduleListItemStaff.jsx

✨ 스케줄 관리 기능 개선: 경로 파라미터 추가 및 사용자 권한 체크 수정

---

src/api/authApi.js
src/pages/ProfilePage.jsx

🐛 Current_password

---

src/api/authApi.js

🐛 CurrentpasswordApi

---

src/App.jsx

📝 LastActivity

---

src/pages/SchedulePage.jsx
src/styles/calendar.css

✨ Feat : 충돌 및 css 분리

---

src/pages/SchedulePage.jsx
src/styles/calendar.css

Revert "✨ Feat : 충돌 및 css 분리"

---

src/pages/SchedulePage.jsx
src/styles/SchedulePage.css

✨ Feat : 달력 라이브러리 대신 생성

---

src/components/MyArtistFilterCard.jsx

✨ 기본 이미지 경로 수정: 아티스트 이미지가 없을 경우 기본 이미지 사용

---

src/components/ScheduleList.jsx
src/pages/SchedulePage.jsx

🐛 SchedulelistApi

---

src/pages/admin/schedule/ScheduleAddPage.jsx

✨ Feat: 스케줄 추가 페이지에서 그룹 및 솔로 스케줄 생성 시 내비게이션 추가 및 오류 처리 개선

---

src/api/useFetchAdvertisements.js
src/components/BannerAd.jsx

✨ BannerApi

---

src/components/ScheduleList.jsx
src/components/ScheduleListItem.jsx
src/pages/SchedulePage.jsx

✨ Calendarfiltering

---

index.html
src/pages/ScheduleDetailPage.jsx

✨ Feat: 카카오 SDK 초기화 및 공유 기능 추가

---

src/App.jsx
src/components/MyArtistFilterCard.jsx
src/components/ScheduleList.jsx
src/pages/SchedulePage.jsx

좋아요누른 아티스트카드 클릭시 해당아티스트스케줄 생성
스케줄페이지에 추가된 마이아티스트 클릭스 스케줄리스트에 해당아티스트 스케줄 생성
재클릭시 스케줄리스트가 전체일정으로 변경

✨ Like artist schedules

---

src/App.jsx
src/api/authApi.js
src/store/userStore.js

유저인포 로컬에 남아서 페이지가 무한로딩이되는거 해결 아마도
user_info 로컬에 남아서 강제 종료후 프로젝트 재실행시 무한로딩인거 수정
user_info 로컬에 남아서 로그아웃안하고 강제종료시 페이지가 무한로딩이 상황발생

📝 Userinfolocaldelete

---

src/App.jsx
src/api/googleAuthApi.js
src/api/kakaoAuthapi.js
src/api/naverAuthApi.js
src/components/MyArtistFilter.jsx
src/components/MyArtistFilterCard.jsx
src/components/SocialLogin.jsx
src/pages/AuthCallback.jsx
src/pages/LoginPage.jsx
src/pages/SchedulePage.jsx
src/store/userStore.js

불필요한콘솔로그삭제 스케줄페이지 마이아티스트목록에 전체일정 버튼추가

📝 LogDelete

---

src/components/MyArtistFilterCard.jsx
src/components/ScheduleList.jsx
src/components/ScheduleListItem.jsx
src/pages/ScheduleDetailPage.jsx
src/pages/SchedulePage.jsx

Feature/favorite 아티스트 버튼 눌리면 보더 생기게

---

src/components/ScheduleList.jsx
src/components/ScheduleListItem.jsx

스케줄 시작날짜와 종료날짜에따라 진행중 종료됨 표시
스케줄리스트에 표시된 스케줄 start.data. end.data 에 따라서 진행중,종료됨 표시

✨ Schedulelisting

---

src/App.jsx
src/api/authApi.js
src/api/axiosInterceptors.js
src/api/googleAuthApi.js
src/api/kakaoAuthapi.js
src/api/naverAuthApi.js
src/components/BannerAd.jsx
src/store/userStore.js
src/utils/authUtils.js

이제 진짜 무한로딩 안걸릴지도..
로컬에 이제 로그아웃하면 아무것도 안남게 변경  기존 남아있었음LastActivity

📝 LastActivitylocalDelete

---

src/components/ArtistCard.jsx
src/components/ArtistCardArea.jsx
src/styles/ArtistCardArea.css

✨ Feat : 좋아요한  가수 필터링 & 실시간 랜더링

---

src/pages/SchedulePage.jsx
src/styles/SchedulePage.css

✨ Feat : 좋아요한 아티스트들 스크롤 대신 화살표 스크롤

---

src/store/userStore.js

스케줄 디테일 페이지에서 새로고침 하면 홈으로 가지는 현상 수정

🐛 Fix : 새로고침 시 페이지 유지

---

src/api/googleAuthApi.js
src/api/kakaoAuthapi.js
src/api/naverAuthApi.js

✨ Feat: 인증 URL의 리다이렉트 URI를 배포 환경으로 변경

---

src/pages/SchedulePage.jsx
src/pages/admin/schedule/Index.jsx
src/styles/SchedulePage.css

💄 Style : 관리자 달력 라이브러리 대신 커스텀 달력 변경
즐겨찾기 음표 >> 별표로 수정

💄 Style : 관리자 달력 라이브러리 대신 커스텀 달력 변경

---

src/api/googleAuthApi.js
src/api/kakaoAuthapi.js
src/api/naverAuthApi.js
src/pages/AuthCallback.jsx
src/pages/ProfilePage.jsx
src/store/userStore.js

🐛 Accesstoken

---

src/api/authApi.js
src/api/axiosInterceptors.js
src/api/googleAuthApi.js
src/api/kakaoAuthapi.js
src/api/naverAuthApi.js

🐛 Fix/window

---

src/pages/ForgotPasswordPage.jsx
src/pages/ResetPasswordPage.jsx
src/styles/ResetPassword.css

💄 Style : 비밀번호 찾기 css 추가

---

src/pages/SignupCompletedPage.jsx

✨ Feat: 회원가입 완료 페이지 레이아웃 개선 및 코드 정리

---

src/pages/AdminRequestCompletedPage.jsx
src/pages/ProfilePage.jsx

✨ Feat: 프로필 페이지 레이아웃 개선 및 코드 정리

---

src/api/authApi.js
src/pages/ForgotPasswordPage.jsx

🐛 Fix : 소셜로그인시 비밀번호 찾기 막음

---

src/pages/SchedulePage.jsx
src/pages/admin/schedule/Index.jsx
src/styles/SchedulePage.css

💄 Style : 달력 크기 고정
